### ISSUE TITLE
where to put the "BEAST.base.addon.v2.7.3.zip" file?

### ISSUE THREAD

**Issue by liamxg** [CompEvol/beast2#1111] opened 2023-05-30 08:32 UTC

**Comment by rbouckaert** [comment] 2023-05-31 00:31
The file is a package file best handled through the packagemanager. When you update the `BEAST.base` package, it will be put in the package directory (which differs for different operating systems) and uncompressed there. Only if you want to [install by hand](http://www.beast2.org/managing-packages/#Install_by_hand) should you handle this file.

By the way, the latest version is v2.7.4, so v2.7.3 is out of date and only available for replicability.

This appears to be a user question more appropriate for the [beast-users list](https://groups.google.com/g/beast-users/), not a bug report of feature request, so I close the issue. If you have more detail, please reopen.

**Closed by rbouckaert** 2023-05-31 00:31 UTC
