### ISSUE TITLE
no software does not load after trying upgrade

### ISSUE THREAD

**Issue by desmodus1984** [CompEvol/beast2#850] opened 2019-05-21 04:22 UTC
Hi, I have been using BeautI and Beast2 well, for the last few days - I have mtdna data that I wanted to use to estimate a Bayesian Skyline plot. While reading I found about the Structured Coalescent Package, tried to install MultiTypeTree, as well as the coupled MCMC using the BeautI package installer. While installing/upgrading, the installer got a problem, and stopped. Now any of the Beast 2 installer loads, even using the Run as Administrator option.
What is going on? How can I solve it and use Beast2 again?

**Comment by rbouckaert** [comment] 2019-05-21 06:10
What operating system and BEAST version are you using?

One possible quick fix is to remove the package directory, which is `c:\users\<yourname>\BEAST\2.5` on Windows, `~/Library/Application Support/BEAST/2.5` on OS X and `~/.beast/2.5` on Linux.

**Comment by desmodus1984** [comment] 2019-05-21 06:18
I did eliminate the directory/folder where I unzipped the file, restarted the computer and nothing.
I am using the latest Beast 2 version under Windows 10 Home edition.

**Comment by rbouckaert** [comment] 2019-05-21 06:45
Thanks for that information. It is not sufficient to delete the folder where BEAST is unzipped. BEAST creates a directory where it stores packages -- on Windows this will be `c:\users\<yourname>\BEAST\2.5` where `<yourname>` is your user name on the Windows machine. If something went wrong during the installation of a package, it is possible that deleting that directory will allow BEAST to start again.

To help found out what may have caused the problem in the first place, can you let me know whether you are you using the version with the JRE included or do you have java installed separately> If the latter, which version of java are you using?

**Comment by desmodus1984** [comment] 2019-05-29 20:06
Dear Remco,
I downloaded the version that includes the JRE - I did previously install java - I am using the latest version of java. I did what you suggested- deleting the folder "c:\users\<yourname>\BEAST\2.5" and it is working well. 
I have a question is you don't mind, how do I translate "1.30 × 10−8 subs/site/year" for the substitution rate in BEAUTi?  Thanks;

**Comment by rbouckaert** [comment] 2019-05-29 20:22
Thanks for letting me know -- the problem appears to be caused by the PackageManager.closeClassLoader() method assumes the class loader is a URLClassLoader, while this is not necessarily the case for Java 9 and up. This prevents the package manager from closing things down properly, and it hangs without being able to install new packages.

As for your second question (which is more appropriate for the [beast-user list](https://groups.google.com/forum/#!forum/beast-users), since this facility is only meant to be for reporting bugs), it depends on the units used for your tree. If it is years, 1.30 × 10−8 s/s/y translates to a clock rate of 1.30 × 10−8. If it is millions of years, then you have 1.30 × 10−2 s/s/million year, so it translates to a rate of 1.30 × 10−2.

**Comment by rbouckaert** [comment] 2019-06-10 19:19
Should be fixed by branch issue834 -- see #834 -- which is now merged into master.

**Closed by rbouckaert** 2019-06-10 19:19 UTC
Labels: OS: Windows
