### ISSUE TITLE
Resume should be robust to (small) differences in final state of log and trees file

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#1] opened 2014-01-19 00:45 UTC
### What steps will reproduce the problem?
1. Terminate BEAST prematurely
2. Attempt to resume

### What is the expected output? What do you see instead?
Resumption of MCMC expected, instead failure to resume can sometimes occur:
Error message from Thomas Vignaud:

Start likelihood: -7892.4621158294585 
java.lang.Exception: Error 400: Cannot resume: log files do not end in same sample number
    at beast.core.Logger.openLogFile(Unknown Source)
    at beast.core.Logger.init(Unknown Source)
    at beast.core.MCMC.run(Unknown Source)
    at beast.app.BeastMCMC.run(Unknown Source)
    at beast.app.beastapp.BeastMain.<init>(Unknown Source)
    at beast.app.beastapp.BeastMain.main(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at apple.launcher.LaunchRunner.run(LaunchRunner.java:116)
    at apple.launcher.LaunchRunner.callMain(LaunchRunner.java:51)
    at apple.launcher.JavaApplicationLauncher.launch(JavaApplicationLauncher.java:52)

**Comment by rbouckaert** [comment] 2016-06-21 04:15
duplicate of #430

**Closed by rbouckaert** 2016-06-21 04:15 UTC
Labels: defect, HIGH priority
