### ISSUE TITLE
It's possible to set up and run analyses on serial data with ultrametric-only tree priors

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#727] opened 2017-08-18 10:16 UTC
In BEAUti it's possible to set non-contemporaneous sample times, select a tree prior (eg Yule or BD) that cannot be sensibly applied to non-ultrametric trees.  Currently a warning is produced (small red "x" to the right of the tree prior), but it's still possible to save the resulting XML file.

Once the XML is produced, it is also possible to run BEAST using this file.  BEAST produces a warning message, but this is often only displayed briefly (a fraction of a second) and the analysis then proceeds without any indication that something is wrong.

In my opinion the best course would be for 1) BEAUti to refuse to save such an XML and 2) BEAST to refuse to run such an analysis.

**Comment by rbouckaert** [comment] 2018-03-05 02:14
Duplicate of #608.

**Closed by rbouckaert** 2018-03-05 02:14 UTC
Labels: BEAUti, MEDIUM priority
