### ISSUE TITLE
Implement ModelTest models

### ISSUE THREAD

**Issue by alexeid** [CompEvol/beast2#267] opened 2015-02-16 20:04 UTC
Many users apply ModelTest to chose substitution models. We should allow easy selection of all the substitution models that ModelTest (and jModelTest2) can produce.

**Comment by rbouckaert** [comment] 2017-05-26 23:58
Now implemented in [SSM](https://github.com/BEAST2-Dev/substmodels) package.
 
Duplicate of #597

**Closed by rbouckaert** 2017-05-26 23:58 UTC
Labels: BEAUti, MEDIUM priority
