### ISSUE TITLE
Error 110 parsing the xml input file: Cannot find taxon MyTAXON in data

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#37] opened 2014-01-19 04:34 UTC
Hey Carlos,

Yes... that is a bug in Beauty I think... I got the same issue... It creates new elements using "id" (and adds 1 to pre-existing taxa names) instead of referring directly to those using "idref"

In my case I had to replace:

```xml
                <taxonset id="Ingroup" spec="TaxonSet">
                    <taxon id="aiensis1" spec="Taxon"/>
                    <taxon id="cynocephalus1" spec="Taxon"/>
                    <taxon id="eudentatus1" spec="Taxon"/>
                    <taxon id="franouxi1" spec="Taxon"/>
                    <taxon id="hageni1" spec="Taxon"/>
                    <taxon id="japonicus1" spec="Taxon"/>
                    <taxon id="lagocephalus1" spec="Taxon"/>
                    <taxon id="lenguru1" spec="Taxon"/>
                    <taxon id="lividus1" spec="Taxon"/>
                    <taxon id="longifilis1" spec="Taxon"/>
                    <taxon id="marquesensis1" spec="Taxon"/>
                    <taxon id="ouwensi1" spec="Taxon"/>
                    <taxon id="pugnans1" spec="Taxon"/>
                    <taxon id="punctissimus1" spec="Taxon"/>
                    <taxon id="rapa1" spec="Taxon"/>
                    <taxon id="sarasini1" spec="Taxon"/>
                    <taxon id="spBIF1" spec="Taxon"/>
                    <taxon id="stimpsoni1" spec="Taxon"/>
                    <taxon id="stiphodonoides1" spec="Taxon"/>
                </taxonset>
```
by this
```xml
                <taxonset id="Ingroup" spec="TaxonSet">
                    <taxon idref="aiensis"/>
                    <taxon idref="cynocephalus"/>
                    <taxon idref="eudentatus"/>
                    <taxon idref="franouxi"/>
                    <taxon idref="hageni"/>
                    <taxon idref="japonicus"/>
                    <taxon idref="lagocephalus"/>
                    <taxon idref="lenguru"/>
                    <taxon idref="lividus"/>
                    <taxon idref="longifilis"/>
                    <taxon idref="marquesensis"/>
                    <taxon idref="ouwensi"/>
                    <taxon idref="pugnans"/>
                    <taxon idref="punctissimus"/>
                    <taxon idref="rapa"/>
                    <taxon idref="sarasini"/>
                    <taxon idref="spBIF"/>
                    <taxon idref="stimpsoni"/>
                    <taxon idref="stiphodonoides"/>
                </taxonset>
```

### Additional comments on GC issue
 Project Member #1 higgs.ml

What should be done to reproduce this one?

Remco

**Comment by rbouckaert** [comment] 2016-02-29 20:37
duplicate of #478

**Closed by rbouckaert** 2016-02-29 20:37 UTC
Labels: BEAUti, defect, MEDIUM priority
