### ISSUE TITLE
Importing nexus files using BEAUti's -nex argument breaks things

### ISSUE THREAD

**Issue by tgvaughan** [CompEvol/beast2#842] opened 2019-03-29 10:41 UTC
To reproduce:

1. Start beauti from the command line in the BEAST2 package directory with the command
```
$ beauti -nex examples/nexus/Primates.nex
```
2. Select both partitions in the alignment panel and click "link clock models".

3. Switch to the priors panel and observe that one of the clock rates (clockRate.c:secondHalf) is still estimated.

4. Save the XML and observe that while the clock rate assigned to the branch model for the trees is fixed, a clock rate parameter is still estimated.  An improper prior exists for this parameter, so the result will be an MCMC chain with a parameter that diverges to infinity.

Repeating exactly the same steps but loading the alignment via the GUI does not produce this problem.

**Comment by rbouckaert** [comment] 2019-03-31 20:16
This is caused by the TreeLikelihood creating a BeagleTreeLikelihood with the same clock model when starting from the CLI. When linking the clock model in BEAUti, we are editing the input to TreeLikelihood, but not to BeagleTreeLikelihood, so the clock model for the 2nd partition is still in the posterior, and thus BEAUti concludes that clockRate.c:secondHalf still needs to be estimated.

If TreeLikelihood knows it is created in BEAUti, it does not create a BeagleTreeLikelihood, but currently the flag is set after parsing CLI arguments. This is fixed by setting the flag before parsing arguments.

**Closed** 2019-03-31 20:16 UTC
Labels: BEAUti, MEDIUM priority, defect
