### ISSUE TITLE
RNA data and BeagleTreeLikelihood act weird

### ISSUE THREAD

**Issue by rbouckaert** [CompEvol/beast2#736] opened 2017-10-03 00:21 UTC
BEAGLE and Java TreeLikelihoods give different results. To reproduce, import RNA alignment into BEAUti (containing Us instead of Ts), set subst model to HKY. Run BEAST with BEAGLE and without BEAGLE. If you do this with beast2/examples/nexus/dna.nex with Ts replaced by Us the likelihood with java is around -5000, but with beagle around -3000. It appears the Us are interpreted as ambigous characters with the BeagleTreeLiklihood, but not with the java TreeLikelihood.

**Comment by tgvaughan** [comment] 2017-10-03 07:18
Yikes

**Comment by alexeid** [comment] 2017-10-03 07:40
Ouch!

**Comment by tgvaughan** [comment] 2017-10-03 07:50
So replacing Us with Ns causes the java likelihood to produce exactly the same result as beagle?

**Comment by tgvaughan** [comment] 2017-10-11 18:58
Here's a  [minimal example](https://github.com/CompEvol/beast2/files/1376671/tinyRNAtest.xml.txt) which reproduces this problem.  It's a single XML file containing two 3-taxon alignments: one ("alignU") containing only Us, the other ("alignT") containing only Ts.  The datatype is nucleotide in both cases.  It describes an MCMC chain of length 2 starting from a random tree.

With BEAGLE enabled, this produces a logL of 0 for alignU and something on the order of -1 for alignT.  With BEAGLE disabled (using the -java switch), the logL values for both alignU and alignT are identical and on the order of -1.

As Remco suggested, I think this is due to the BEAGLE code misclasifying the U as an ambiguous state.  By default this means that it's treated as a gap character and in this particular alignment that means that there are no non-gap characters, hence the logL of 0.

I'm pretty sure the actual culprit is the BeagleTreeLikelihood::setStates, which currently looks like this:
```java
    protected final void setStates(Beagle beagle,
                                   int nodeIndex, int taxon) {
        Alignment data = dataInput.get();
        int i;

        int[] states = new int[patternCount];

        for (i = 0; i < patternCount; i++) {
            int state = data.getPattern(taxon, i);
            states[i] = state;
        }

        beagle.setTipStates(nodeIndex, states);
    }
```

Here `data` is a field containing the instance of `Alignment` the likelihood is begin computed for.  The `data.getPattern(taxon,i)` call gets an integer representation of the character on taxon `taxon`  in pattern `i`.  However, this integer representation is a literal representation of the character: every character in the datatype's alphabet, including characters representing ambiguities, corresponds to a distinct integer.  So in this representation, U and T have different numbers.

In contrast, number `state` should take into account the equivalence of certain characters (such as U and T).  The corresponding `BeagleTreeLikelihood::getPartials` method does this (when handling of ambiguities is enabled) by calling `data.getStateSet(code)` where `code` is the result of `data.getPattern(taxon,i)`.  Thus it's not surprising that when useAmbiguities="true" in the alignU likelihood, BEAGLE starts returning the the same logL as for alignT.

Compare the above method with `TreeLikelihood::setStates`:
```java
    protected void setStates(Node node, int patternCount) {
        if (node.isLeaf()) {
            Alignment data = dataInput.get();
            int i;
            int[] states = new int[patternCount];
            int taxonIndex = getTaxonIndex(node.getID(), data);
            for (i = 0; i < patternCount; i++) {
                int code = data.getPattern(taxonIndex, i);
                int[] statesForCode = data.getDataType().getStatesForCode(code);
                if (statesForCode.length==1)
                    states[i] = statesForCode[0];
                else
                    states[i] = code; // Causes ambiguous states to be ignored.
            }
            likelihoodCore.setNodeStates(node.getNr(), states);

        } else {
            setStates(node.getLeft(), patternCount);
            setStates(node.getRight(), patternCount);
        }
    }
```

You can see here that the result of `data.getPattern()` is passed to `data.getDataType().getStatesForCode()`.  This has a similar effect of mapping a given character code onto a vector of the state distribution implied by the character.  Both T and U map to the same state, which is why things work out when TreeLikelihood rather than BeagleTreeLikelihood is used.

I've implemented a quick fix to `BeagleTreeLikelihood::setStates` which uses the relevant portion of the code from `TreeLikelihood::setStates`.  This fixes the problem in the minimal example at least, and hopefully elsewhere as well.  Please let me know if you think this solves the issue so we can mark it as closed.

I'll add a unit test for the problem too as soon as I can.

**Comment by tgvaughan** [comment] 2017-10-12 07:22
Bumping this bug up to critical, as it has the capacity to silently break a wide range of analyses.

**Comment by alexeid** [comment] 2017-10-12 07:36
It is a bug with BEAGLE or with the BEAST2 wrapper class for BEAGLE? If second one I think this is serious enough to warrant its own minor release pronto.

**Comment by tgvaughan** [comment] 2017-10-12 07:44
It's a bug in the BEAST2 wrapper class, BeagleTreeLikelihood.

**Comment by rambaut** [comment] 2017-10-12 07:45
I think it must be a problem with the wrapper class. BEAGLE takes state indices 0-3 to denote nucleotides and anything > 3 is treated as completely ambiguous. BEAST 1 code maps both T and U to state index 3. I assume BEAST2 is not seeing them as synonymous and is giving U its own index (4?).

**Comment by tgvaughan** [comment] 2017-10-12 07:54
Thanks Andrew, that's right: see my analysis above.  I've committed a fix that seems to work (and a corresponding unit test), but just waiting on someone to review it before closing this issue.

**Comment by rambaut** [comment] 2017-10-12 08:14
Just seen your analysis, it makes sense. This may affect people doing (RNA) virus work as it tends to vary whether sequence are denoted as RNA or DNA and some alignments could have a mixture of both. 

A.

**Comment by tgvaughan** [comment] 2017-10-12 16:43
Great, thanks Andrew.  I'll mark this as closed.  (And I agree with Alexei that we then need to release the patched version immediately.)

**Closed by tgvaughan** 2017-10-12 16:43 UTC
Labels: CRITICAL priority, defect
