### ISSUE TITLE
Logging at different rates in .log and .trees files makes resume impossible

### ISSUE THREAD

**Issue by bjoelle** [CompEvol/beast2#430] opened 2015-09-21 14:26 UTC
When 'logEvery' is set to different numbers for the .log and the .trees file, resume will fail with the following error 
java.lang.Exception: Error 401: Cannot resume: log files do not end in same sample number
    at beast.core.Logger.openLogFile(Unknown Source)
    at beast.core.Logger.init(Unknown Source)
    at beast.core.MCMC.run(Unknown Source)
    at beast.app.BeastMCMC.run(Unknown Source)
    at beast.app.beastapp.BeastMain.<init>(Unknown Source)
    at beast.app.beastapp.BeastMain.main(Unknown Source)

Possible fix: using the sample number from the .state file instead ?

**Comment by rbouckaert** [comment] 2015-09-21 19:42
This is related to #1

**Comment by Graham853** [comment] 2016-02-03 12:58
Under Windows, I get this error message instead:
`File error: C:\Users\Work\Desktop\resume\26.trees -> C:\Users\Work\Desktop\resume\26.trees: The process cannot access the file because it is being used by another process.`

Example files attached.

[x.zip](https://github.com/CompEvol/beast2/files/115645/x.zip)

**Comment by walterxie** [comment] 2018-06-15 03:05
Cannot replicate, must be solved in #1

**Comment by tgvaughan** [comment] 2018-06-15 06:50
I can replicate this.  I think issue #1 was not closed because it was fixed, but because it was a duplicate of this issue.  (Ideally this issue should have been closed and issue #1 kept as it is far older, but it doesn't really matter.)

**Comment by rbouckaert** [comment] 2020-06-03 23:00
Commit 89ae738 assumes files are not corrupted, just that they have different states logged.

**Closed** 2020-06-03 23:30 UTC
Labels: HIGH priority, defect

**Comment by rbouckaert** [comment] 2020-06-03 23:32
On finding out the last state of a trace log, the logger now removes the last line if it does not contain the same number of columns as the header.
For tree files, the last line is removed if the last line does not end in a semi-column, which indicates the tree writing process was interrupted.
