### ISSUE TITLE
Fatal exception: StarBEAST2 using fullInit to initialize all trees

### ISSUE THREAD

**Issue by alexeid** [CompEvol/beast2#628] opened 2016-10-20 00:17 UTC
Huw: "This seems to happen if alignment files are dragged-and-dropped into the "Partitions" tab, instead of using the "+" button to add alignments."

Error message from Shea on beast-users:

"StarBEAST2: using fullInit to initialize all trees.
Fatal exception: Cannot find taxon 1 in data
java.lang.RuntimeException: Cannot find taxon 1 in data
    at beast.math.distributions.MRCAPrior.initialise(Unknown Source)
    at beast.math.distributions.MRCAPrior.calculateLogP(Unknown Source)
    at beast.core.util.CompoundDistribution.calculateLogP(Unknown Source)
    at beast.core.util.CompoundDistribution.calculateLogP(Unknown Source)
    at beast.core.State.robustlyCalcPosterior(Unknown Source)
    at beast.core.MCMC.run(Unknown Source)
    at beast.app.BeastMCMC.run(Unknown Source)
    at beast.app.beastapp.BeastMain.<init>(Unknown Source)
    at beast.app.beastapp.BeastMain.main(Unknown Source)
    at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Fatal exception: Cannot find taxon 1 in data
java.lang.RuntimeException: An error was encounted. Terminating BEAST
    at beast.app.util.ErrorLogHandler.publish(Unknown Source)
    at java.util.logging.Logger.log(Logger.java:738)
    at java.util.logging.Logger.doLog(Logger.java:765)
    at java.util.logging.Logger.log(Logger.java:788)
    at java.util.logging.Logger.severe(Logger.java:1463)
    at beast.app.beastapp.BeastMain.<init>(Unknown Source)
    at beast.app.beastapp.BeastMain.main(Unknown Source)
    at beast.app.beastapp.BeastLauncher.main(Unknown Source)"

**Comment by genomescale** [comment] 2016-10-20 04:54
This behaviour manifests on Linux and on macOS, so it is not platform-specific.

**Comment by walterxie** [comment] 2016-10-27 01:29
After my test, this function works for standard and *BEAST template. It is therefore a normal defect caused by adding new feature as my understanding. The priority should be normal.

I agree the "+ button" and "drag drop" function should share the same code, but this will be solved in a separated issue.  

Huw, I am willing to help if you forward me Shea's XML.
Cheers,
Walter

**Comment by alexeid** [comment] 2016-10-27 15:37
If you haven’t replicated the error how can you say if it is severe or not?

Alexei

**Comment by walterxie** [comment] 2016-10-27 20:25
Because the error does not happen to "core functions" as I investigated. Unless someone could prove it, using "Critical" to an unknown problem in a development version is really disturbed.

**Comment by alexeid** [comment] 2016-10-27 21:05
StarBEAST2 is a core function and already released.

**Comment by walterxie** [comment] 2016-10-30 21:51
Hi, Huw, can you please test the current code with the fix of #631? If it works, then I will close this issue.
@genomescale

**Comment by genomescale** [comment] 2016-10-31 00:29
Hi Walter, it looks like drag-and-drop works with StarBEAST2 using the latest code. Thanks for fixing the issue.

**Closed** 2016-10-31 00:30 UTC
Labels: BEAUti, defect
